lib/snowtrack_web/router.ex
defmodule SnowtrackWeb.Router do
  use SnowtrackWeb, :router

  import SnowtrackWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SnowtrackWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Other scopes may use custom stacks.
  # scope "/api", SnowtrackWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: SnowtrackWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  # Landing routes

  scope "/", SnowtrackWeb do
    pipe_through :browser

    live "/", Landing.LandingLive
  end

  ## Authentication routes

  scope "/", SnowtrackWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    live_session :unregistered do
      live "/login", Accounts.LoginLive
      live "/register", Accounts.RegisterLive
      live "/users/confirm/:token", Accounts.ConfirmLive
      live "/users/request_password_reset", Accounts.RequestPasswordResetLive
      live "/users/reset_password/:token", Accounts.ResetPasswordLive
      live "/users/unconfirmed", Accounts.UnconfirmedLive
    end

    get "/users/login/email/:email/login_token/:login_token",
        Accounts.UserSessionController,
        :create_from_login_token
  end

  scope "/", SnowtrackWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SnowtrackWeb do
    pipe_through [:browser]

    delete "/users/log_out", Accounts.UserSessionController, :delete
  end
end

lib/snowtrack_web/views/layout_view.ex
defmodule SnowtrackWeb.LayoutView do
  use SnowtrackWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/snowtrack_web/templates/layout/_user_menu.html.heex
<ul>
  <%= if @current_user do %>
    <li><%= @current_user.email %></li>
    <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></li>
    <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
  <% else %>
  <% end %>
</ul>

lib/snowtrack_web/templates/layout/app.html.heex
<main>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
  <%= render "_user_menu.html", assigns %>
</main>

lib/snowtrack_web/templates/layout/live.html.heex
<main class="relative">
  <.flash flash={@flash} kind={:info}/>
    <.flash flash={@flash} kind={:error}/>
      <%= @inner_content %>
    </main>

lib/snowtrack_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="180x180" href="/images/icon/apple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="/images/icon/favicon-32x32.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="/images/icon/favicon-16x16.png" />
    <link rel="manifest" href="/site.webmanifest" />
    <meta name="msapplication-config" content="/browserconfig.xml" />
    <meta name="msapplication-TileColor" content="#0F172A" />
    <meta name="theme-color" content="#0F172A" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tag() %>
    <%= live_title_tag(assigns[:page_title] || "Mobile Analytics", suffix: " · Snowtrack") %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <script
      defer
      phx-track-static
      type="text/javascript"
      src={Routes.static_path(@conn, "/assets/app.js")}
    ></script>
  </head>
  <body class="antialiased text-slate-400 bg-slate-900">
    <%= @inner_content %>
  </body>
</html>